---

- name: Install python tools
  package:
    name:
      - virtualenv
      - python3
      - python3-dev
      - python3-pip
    state: present

- name: Install requirements
  pip: 
    name:
      - deepspeech-gpu
      - git+https://github.com/constructorfleet/deepspeech-server.git#deepspeech-server
    virtualenv: "{{ deepspeech_install_location }}"
    virtualenv_python: python3

- name: Deepseech server config file
  template:
    src: deepspeech-server-config.json.j2
    dest: "{{ deepspeech_server_config_path }}"
    owner: root
    group: root
    mode: "644"
