---

- name: Install python tools
  package:
    name:
      - virtualenv
      - python3
      - python3-dev
      - python3-pip
    state: present

- name: Install requirements
  pip: 
    name:
      - deepspeech-gpu
    virtualenv: "{{ deepspeech_install_location }}"
    virtualenv_python: python3
